version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etldb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  etl:
    build: ./etl
    container_name: etl_week_3
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    env_file:
      - .env
